# Generated by Django 3.2.5 on 2022-03-02 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverTrendSearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ratio', models.FloatField()),
                ('company', models.CharField(max_length=25)),
            ],
            options={
                'unique_together': {('date', 'company')},
            },
        ),
        migrations.CreateModel(
            name='DCInsideDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(db_index=True)),
                ('content', models.TextField(null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.dcinsidetitlemodel')),
            ],
        ),
    ]
