# Generated by Django 4.0.2 on 2022-03-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_dcinsidedetailmodel_navertrendsearchmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecastResultModel',
            fields=[
                ('company', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('demand_forecast_date', models.DateField(db_index=True, null=True)),
                ('ipo_price', models.IntegerField()),
                ('ipo_value', models.IntegerField()),
                ('institutional_competition_rate', models.FloatField()),
                ('hold_rate', models.FloatField()),
                ('security', models.CharField(max_length=20)),
                ('hope_price_min', models.IntegerField()),
                ('hope_price_max', models.IntegerField()),
            ],
        ),
    ]
